# coding: utf-8

"""
    Flojoy Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.workspace_get_workspace_by_id_default_response import WorkspaceGetWorkspaceByIdDefaultResponse

class TestWorkspaceGetWorkspaceByIdDefaultResponse(unittest.TestCase):
    """WorkspaceGetWorkspaceByIdDefaultResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceGetWorkspaceByIdDefaultResponse:
        """Test WorkspaceGetWorkspaceByIdDefaultResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceGetWorkspaceByIdDefaultResponse`
        """
        model = WorkspaceGetWorkspaceByIdDefaultResponse()
        if include_optional:
            return WorkspaceGetWorkspaceByIdDefaultResponse(
                message = '',
                code = '',
                issues = [
                    openapi_client.models.workspace_get_workspace_by_id_default_response_issues_inner.workspace_getWorkspaceById_default_response_issues_inner(
                        message = '', )
                    ]
            )
        else:
            return WorkspaceGetWorkspaceByIdDefaultResponse(
                message = '',
                code = '',
        )
        """

    def testWorkspaceGetWorkspaceByIdDefaultResponse(self):
        """Test WorkspaceGetWorkspaceByIdDefaultResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
