# coding: utf-8

"""
    Flojoy Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.test_get_all_tests_by_project_id200_response_inner import TestGetAllTestsByProjectId200ResponseInner

class TestTestGetAllTestsByProjectId200ResponseInner(unittest.TestCase):
    """TestGetAllTestsByProjectId200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TestGetAllTestsByProjectId200ResponseInner:
        """Test TestGetAllTestsByProjectId200ResponseInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TestGetAllTestsByProjectId200ResponseInner`
        """
        model = TestGetAllTestsByProjectId200ResponseInner()
        if include_optional:
            return TestGetAllTestsByProjectId200ResponseInner(
                id = '',
                measurement_type = 'boolean',
                name = '',
                project_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return TestGetAllTestsByProjectId200ResponseInner(
                id = '',
                measurement_type = 'boolean',
                name = '',
                project_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testTestGetAllTestsByProjectId200ResponseInner(self):
        """Test TestGetAllTestsByProjectId200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
