# coding: utf-8

"""
    Flojoy Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.measurement_api import MeasurementApi


class TestMeasurementApi(unittest.TestCase):
    """MeasurementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MeasurementApi()

    def tearDown(self) -> None:
        pass

    def test_measurement_create_measurement(self) -> None:
        """Test case for measurement_create_measurement

        """
        pass

    def test_measurement_get_all_measurements_by_test_id(self) -> None:
        """Test case for measurement_get_all_measurements_by_test_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
