# coding: utf-8

"""
    Flojoy Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.workspace_get_workspace_by_id200_response import WorkspaceGetWorkspaceById200Response

class TestWorkspaceGetWorkspaceById200Response(unittest.TestCase):
    """WorkspaceGetWorkspaceById200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceGetWorkspaceById200Response:
        """Test WorkspaceGetWorkspaceById200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceGetWorkspaceById200Response`
        """
        model = WorkspaceGetWorkspaceById200Response()
        if include_optional:
            return WorkspaceGetWorkspaceById200Response(
                id = '',
                name = '',
                plan_type = 'hobby',
                total_seats = 1.337,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return WorkspaceGetWorkspaceById200Response(
                id = '',
                name = '',
                plan_type = 'hobby',
                total_seats = 1.337,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testWorkspaceGetWorkspaceById200Response(self):
        """Test WorkspaceGetWorkspaceById200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
