# coding: utf-8

"""
    Flojoy Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.test_get_test_by_id200_response_measurements_inner_device import TestGetTestById200ResponseMeasurementsInnerDevice

class TestTestGetTestById200ResponseMeasurementsInnerDevice(unittest.TestCase):
    """TestGetTestById200ResponseMeasurementsInnerDevice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TestGetTestById200ResponseMeasurementsInnerDevice:
        """Test TestGetTestById200ResponseMeasurementsInnerDevice
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TestGetTestById200ResponseMeasurementsInnerDevice`
        """
        model = TestGetTestById200ResponseMeasurementsInnerDevice()
        if include_optional:
            return TestGetTestById200ResponseMeasurementsInnerDevice(
                id = '',
                name = '',
                project_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return TestGetTestById200ResponseMeasurementsInnerDevice(
                id = '',
                name = '',
                project_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testTestGetTestById200ResponseMeasurementsInnerDevice(self):
        """Test TestGetTestById200ResponseMeasurementsInnerDevice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
