# coding: utf-8

"""
    Flojoy Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.workspace_get_workspace_by_id_default_response_issues_inner import WorkspaceGetWorkspaceByIdDefaultResponseIssuesInner

class TestWorkspaceGetWorkspaceByIdDefaultResponseIssuesInner(unittest.TestCase):
    """WorkspaceGetWorkspaceByIdDefaultResponseIssuesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceGetWorkspaceByIdDefaultResponseIssuesInner:
        """Test WorkspaceGetWorkspaceByIdDefaultResponseIssuesInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceGetWorkspaceByIdDefaultResponseIssuesInner`
        """
        model = WorkspaceGetWorkspaceByIdDefaultResponseIssuesInner()
        if include_optional:
            return WorkspaceGetWorkspaceByIdDefaultResponseIssuesInner(
                message = ''
            )
        else:
            return WorkspaceGetWorkspaceByIdDefaultResponseIssuesInner(
                message = '',
        )
        """

    def testWorkspaceGetWorkspaceByIdDefaultResponseIssuesInner(self):
        """Test WorkspaceGetWorkspaceByIdDefaultResponseIssuesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
