# coding: utf-8

"""
    Flojoy Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.workspace_api import WorkspaceApi


class TestWorkspaceApi(unittest.TestCase):
    """WorkspaceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkspaceApi()

    def tearDown(self) -> None:
        pass

    def test_workspace_delete_workspace_by_id(self) -> None:
        """Test case for workspace_delete_workspace_by_id

        """
        pass

    def test_workspace_get_all_workspaces(self) -> None:
        """Test case for workspace_get_all_workspaces

        """
        pass

    def test_workspace_get_workspace_by_id(self) -> None:
        """Test case for workspace_get_workspace_by_id

        """
        pass

    def test_workspace_update_workspace(self) -> None:
        """Test case for workspace_update_workspace

        """
        pass


if __name__ == '__main__':
    unittest.main()
