# coding: utf-8

"""
    Flojoy Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.project_api import ProjectApi


class TestProjectApi(unittest.TestCase):
    """ProjectApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectApi()

    def tearDown(self) -> None:
        pass

    def test_project_create_project(self) -> None:
        """Test case for project_create_project

        """
        pass

    def test_project_get_all_projects_by_workspace_id(self) -> None:
        """Test case for project_get_all_projects_by_workspace_id

        """
        pass

    def test_project_get_project_by_id(self) -> None:
        """Test case for project_get_project_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
