# coding: utf-8

"""
    Flojoy Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.test_create_test_request import TestCreateTestRequest

class TestTestCreateTestRequest(unittest.TestCase):
    """TestCreateTestRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TestCreateTestRequest:
        """Test TestCreateTestRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TestCreateTestRequest`
        """
        model = TestCreateTestRequest()
        if include_optional:
            return TestCreateTestRequest(
                name = '',
                project_id = '',
                measurement_type = 'boolean'
            )
        else:
            return TestCreateTestRequest(
                name = '',
                project_id = '',
                measurement_type = 'boolean',
        )
        """

    def testTestCreateTestRequest(self):
        """Test TestCreateTestRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
