# coding: utf-8

"""
    Flojoy Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.device_api import DeviceApi


class TestDeviceApi(unittest.TestCase):
    """DeviceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeviceApi()

    def tearDown(self) -> None:
        pass

    def test_device_create_device(self) -> None:
        """Test case for device_create_device

        """
        pass

    def test_device_delete_device_by_id(self) -> None:
        """Test case for device_delete_device_by_id

        """
        pass

    def test_device_get_all_devices_by_project_id(self) -> None:
        """Test case for device_get_all_devices_by_project_id

        """
        pass

    def test_device_get_device_by_id(self) -> None:
        """Test case for device_get_device_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
