# coding: utf-8

"""
    Flojoy Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.project_create_project_request import ProjectCreateProjectRequest

class TestProjectCreateProjectRequest(unittest.TestCase):
    """ProjectCreateProjectRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectCreateProjectRequest:
        """Test ProjectCreateProjectRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectCreateProjectRequest`
        """
        model = ProjectCreateProjectRequest()
        if include_optional:
            return ProjectCreateProjectRequest(
                name = '',
                workspace_id = ''
            )
        else:
            return ProjectCreateProjectRequest(
                name = '',
                workspace_id = '',
        )
        """

    def testProjectCreateProjectRequest(self):
        """Test ProjectCreateProjectRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
