version: "3"

services:
  flojoy-cloud-next:
    depends_on:
      - flojoy-cloud-postgres
    container_name: flojoy-cloud-next
    build:
      context: ./
      dockerfile: ./docker/dev.Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set environment variables based on the .env file
    env_file:
      - .env.local
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000

  flojoy-cloud-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

networks:
  flojoy-cloud-network:
    external: true
