version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=flojoy-cloud
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
