version: "3"

services:
  flojoy-cloud-next:
    container_name: flojoy-cloud-next
    depends_on:
      flojoy-cloud-postgres:
        condition: service_healthy
    build:
      context: ./
      dockerfile: ./docker/prod.Dockerfile
    env_file:
      - .env.production
    restart: always
    ports:
      - 3000:3000

  flojoy-cloud-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  flojoy-cloud-network:
    external: true
