version: "3"

services:
  cloud-app:
    container_name: cloud-app
    build:
      context: .
      dockerfile: ./apps/frontend/docker/Dockerfile
    restart: on-failure
    env_file: .env
    ports:
      - 3000:3000
