// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { hardwareId, type HardwareId } from "./Hardware";
import {
  type ColumnType,
  type Selectable,
  type Insertable,
  type Updateable,
} from "kysely";
import { z } from "zod";

/** Represents the table public.hardware_relation */
export default interface HardwareRelationTable {
  /** Database type: pg_catalog.text */
  parentHardwareId: ColumnType<HardwareId, HardwareId, HardwareId>;

  /** Database type: pg_catalog.text */
  childHardwareId: ColumnType<HardwareId, HardwareId, HardwareId>;
}

export type HardwareRelation = Selectable<HardwareRelationTable>;

export type NewHardwareRelation = Insertable<HardwareRelationTable>;

export type HardwareRelationUpdate = Updateable<HardwareRelationTable>;

export const hardwareRelation = z.object({
  parentHardwareId: hardwareId,
  childHardwareId: hardwareId,
});

export const hardwareRelationInitializer = z.object({
  parentHardwareId: hardwareId,
  childHardwareId: hardwareId,
});

export const hardwareRelationMutator = z.object({
  parentHardwareId: hardwareId.optional(),
  childHardwareId: hardwareId.optional(),
});
