// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Represents the enum public.plan_type */
type PlanType = 
  | 'hobby'
  | 'pro'
  | 'enterprise';

export default PlanType;

/** Zod schema for plan_type */
export const planType = z.enum([
  'hobby',
  'pro',
  'enterprise',
]);;
