// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Represents the enum public.storage_provider */
type StorageProvider = 
  | 's3'
  | 'postgres';

export default StorageProvider;

/** Zod schema for storage_provider */
export const storageProvider = z.enum([
  's3',
  'postgres',
]);
