// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Represents the enum public.workspace_role */
type WorkspaceRole = 
  | 'owner'
  | 'admin'
  | 'member';

export default WorkspaceRole;

/** Zod schema for workspace_role */
export const workspaceRole = z.enum([
  'owner',
  'admin',
  'member',
]);;
