/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicImport } from './routes/_public'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as ProtectedSetupImport } from './routes/_protected/setup'
import { Route as ProtectedWorkspaceIndexImport } from './routes/_protected/workspace/index'
import { Route as ProtectedProfileIndexImport } from './routes/_protected/profile/index'
import { Route as ProtectedWorkspaceNamespaceNamespaceImport } from './routes/_protected/workspace/$namespace/_namespace'
import { Route as ProtectedWorkspaceNamespaceSettingsIndexImport } from './routes/_protected/workspace/$namespace/settings/index'
import { Route as ProtectedWorkspaceNamespaceProjectIndexImport } from './routes/_protected/workspace/$namespace/project/index'
import { Route as ProtectedWorkspaceNamespaceHardwareIndexImport } from './routes/_protected/workspace/$namespace/hardware/index'
import { Route as ProtectedWorkspaceNamespaceNamespaceIndexImport } from './routes/_protected/workspace/$namespace/_namespace/index'
import { Route as ProtectedWorkspaceNamespaceProjectIdIndexImport } from './routes/_protected/workspace/$namespace/project/$id/index'

// Create Virtual Routes

const PublicIndexLazyImport = createFileRoute('/_public/')()
const PublicSignupLazyImport = createFileRoute('/_public/signup')()
const PublicLoginLazyImport = createFileRoute('/_public/login')()
const ProtectedWorkspaceNamespaceImport = createFileRoute(
  '/_protected/workspace/$namespace',
)()

// Create/Update Routes

const PublicRoute = PublicImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const PublicIndexLazyRoute = PublicIndexLazyImport.update({
  path: '/',
  getParentRoute: () => PublicRoute,
} as any).lazy(() => import('./routes/_public/index.lazy').then((d) => d.Route))

const PublicSignupLazyRoute = PublicSignupLazyImport.update({
  path: '/signup',
  getParentRoute: () => PublicRoute,
} as any).lazy(() =>
  import('./routes/_public/signup.lazy').then((d) => d.Route),
)

const PublicLoginLazyRoute = PublicLoginLazyImport.update({
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any).lazy(() => import('./routes/_public/login.lazy').then((d) => d.Route))

const ProtectedSetupRoute = ProtectedSetupImport.update({
  path: '/setup',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedWorkspaceNamespaceRoute =
  ProtectedWorkspaceNamespaceImport.update({
    path: '/workspace/$namespace',
    getParentRoute: () => ProtectedRoute,
  } as any)

const ProtectedWorkspaceIndexRoute = ProtectedWorkspaceIndexImport.update({
  path: '/workspace/',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedProfileIndexRoute = ProtectedProfileIndexImport.update({
  path: '/profile/',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedWorkspaceNamespaceNamespaceRoute =
  ProtectedWorkspaceNamespaceNamespaceImport.update({
    id: '/_namespace',
    getParentRoute: () => ProtectedWorkspaceNamespaceRoute,
  } as any)

const ProtectedWorkspaceNamespaceSettingsIndexRoute =
  ProtectedWorkspaceNamespaceSettingsIndexImport.update({
    path: '/settings/',
    getParentRoute: () => ProtectedWorkspaceNamespaceRoute,
  } as any)

const ProtectedWorkspaceNamespaceProjectIndexRoute =
  ProtectedWorkspaceNamespaceProjectIndexImport.update({
    path: '/project/',
    getParentRoute: () => ProtectedWorkspaceNamespaceRoute,
  } as any)

const ProtectedWorkspaceNamespaceHardwareIndexRoute =
  ProtectedWorkspaceNamespaceHardwareIndexImport.update({
    path: '/hardware/',
    getParentRoute: () => ProtectedWorkspaceNamespaceRoute,
  } as any)

const ProtectedWorkspaceNamespaceNamespaceIndexRoute =
  ProtectedWorkspaceNamespaceNamespaceIndexImport.update({
    path: '/',
    getParentRoute: () => ProtectedWorkspaceNamespaceNamespaceRoute,
  } as any)

const ProtectedWorkspaceNamespaceProjectIdIndexRoute =
  ProtectedWorkspaceNamespaceProjectIdIndexImport.update({
    path: '/project/$id/',
    getParentRoute: () => ProtectedWorkspaceNamespaceRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/_public': {
      preLoaderRoute: typeof PublicImport
      parentRoute: typeof rootRoute
    }
    '/_protected/setup': {
      preLoaderRoute: typeof ProtectedSetupImport
      parentRoute: typeof ProtectedImport
    }
    '/_public/login': {
      preLoaderRoute: typeof PublicLoginLazyImport
      parentRoute: typeof PublicImport
    }
    '/_public/signup': {
      preLoaderRoute: typeof PublicSignupLazyImport
      parentRoute: typeof PublicImport
    }
    '/_public/': {
      preLoaderRoute: typeof PublicIndexLazyImport
      parentRoute: typeof PublicImport
    }
    '/_protected/profile/': {
      preLoaderRoute: typeof ProtectedProfileIndexImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/workspace/': {
      preLoaderRoute: typeof ProtectedWorkspaceIndexImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/workspace/$namespace': {
      preLoaderRoute: typeof ProtectedWorkspaceNamespaceImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/workspace/$namespace/_namespace': {
      preLoaderRoute: typeof ProtectedWorkspaceNamespaceNamespaceImport
      parentRoute: typeof ProtectedWorkspaceNamespaceRoute
    }
    '/_protected/workspace/$namespace/_namespace/': {
      preLoaderRoute: typeof ProtectedWorkspaceNamespaceNamespaceIndexImport
      parentRoute: typeof ProtectedWorkspaceNamespaceNamespaceImport
    }
    '/_protected/workspace/$namespace/hardware/': {
      preLoaderRoute: typeof ProtectedWorkspaceNamespaceHardwareIndexImport
      parentRoute: typeof ProtectedWorkspaceNamespaceImport
    }
    '/_protected/workspace/$namespace/project/': {
      preLoaderRoute: typeof ProtectedWorkspaceNamespaceProjectIndexImport
      parentRoute: typeof ProtectedWorkspaceNamespaceImport
    }
    '/_protected/workspace/$namespace/settings/': {
      preLoaderRoute: typeof ProtectedWorkspaceNamespaceSettingsIndexImport
      parentRoute: typeof ProtectedWorkspaceNamespaceImport
    }
    '/_protected/workspace/$namespace/project/$id/': {
      preLoaderRoute: typeof ProtectedWorkspaceNamespaceProjectIdIndexImport
      parentRoute: typeof ProtectedWorkspaceNamespaceImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  ProtectedRoute.addChildren([
    ProtectedSetupRoute,
    ProtectedProfileIndexRoute,
    ProtectedWorkspaceIndexRoute,
    ProtectedWorkspaceNamespaceRoute.addChildren([
      ProtectedWorkspaceNamespaceNamespaceRoute.addChildren([
        ProtectedWorkspaceNamespaceNamespaceIndexRoute,
      ]),
      ProtectedWorkspaceNamespaceHardwareIndexRoute,
      ProtectedWorkspaceNamespaceProjectIndexRoute,
      ProtectedWorkspaceNamespaceSettingsIndexRoute,
      ProtectedWorkspaceNamespaceProjectIdIndexRoute,
    ]),
  ]),
  PublicRoute.addChildren([
    PublicLoginLazyRoute,
    PublicSignupLazyRoute,
    PublicIndexLazyRoute,
  ]),
])

/* prettier-ignore-end */
