// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { hardwareId, type HardwareId } from './Hardware';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';
import { z } from 'zod';

/** Represents the table public.hardware_relation */
export default interface HardwareRelationTable {
  parent_hardware_id: ColumnType<HardwareId, HardwareId, HardwareId>;

  child_hardware_id: ColumnType<HardwareId, HardwareId, HardwareId>;
}

export type HardwareRelation = Selectable<HardwareRelationTable>;

export type NewHardwareRelation = Insertable<HardwareRelationTable>;

export type HardwareRelationUpdate = Updateable<HardwareRelationTable>;

export const hardwareRelation = z.object({
  parent_hardware_id: hardwareId,
  child_hardware_id: hardwareId,
});

export const hardwareRelationInitializer = z.object({
  parent_hardware_id: hardwareId,
  child_hardware_id: hardwareId,
});

export const hardwareRelationMutator = z.object({
  parent_hardware_id: hardwareId.optional(),
  child_hardware_id: hardwareId.optional(),
});
