// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { workspaceId, type WorkspaceId } from './Workspace';
import { modelId, type ModelId } from './Model';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';
import { z } from 'zod';

/** Identifier type for public.hardware */
export type HardwareId = string & { __brand: 'HardwareId' };

/** Represents the table public.hardware */
export default interface HardwareTable {
  /** Database type: pg_catalog.text */
  Id: ColumnType<HardwareId, HardwareId, HardwareId>;

  /** Database type: pg_catalog.text */
  Name: ColumnType<string, string, string>;

  /** Database type: pg_catalog.text */
  WorkspaceId: ColumnType<WorkspaceId, WorkspaceId, WorkspaceId>;

  /** Database type: pg_catalog.text */
  ModelId: ColumnType<ModelId, ModelId, ModelId>;

  /** Database type: pg_catalog.timestamptz */
  CreatedAt: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.timestamptz */
  UpdatedAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Hardware = Selectable<HardwareTable>;

export type NewHardware = Insertable<HardwareTable>;

export type HardwareUpdate = Updateable<HardwareTable>;

export const hardwareId = z.string();

export const hardware = z.object({
  Id: hardwareId,
  Name: z.string(),
  WorkspaceId: workspaceId,
  ModelId: modelId,
  CreatedAt: z.date(),
  UpdatedAt: z.date(),
});

export const hardwareInitializer = z.object({
  Id: hardwareId,
  Name: z.string(),
  WorkspaceId: workspaceId,
  ModelId: modelId,
  CreatedAt: z.date().optional(),
  UpdatedAt: z.date().optional(),
});

export const hardwareMutator = z.object({
  Id: hardwareId.optional(),
  Name: z.string().optional(),
  WorkspaceId: workspaceId.optional(),
  ModelId: modelId.optional(),
  CreatedAt: z.date().optional(),
  UpdatedAt: z.date().optional(),
});
