// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';
import { z } from 'zod';

/** Identifier type for public.kysely_migration */
export type KyselyMigrationName = string & { __brand: 'KyselyMigrationName' };

/** Represents the table public.kysely_migration */
export default interface KyselyMigrationTable {
  /** Database type: pg_catalog.varchar */
  Name: ColumnType<KyselyMigrationName, KyselyMigrationName, KyselyMigrationName>;

  /** Database type: pg_catalog.varchar */
  Timestamp: ColumnType<string, string, string>;
}

export type KyselyMigration = Selectable<KyselyMigrationTable>;

export type NewKyselyMigration = Insertable<KyselyMigrationTable>;

export type KyselyMigrationUpdate = Updateable<KyselyMigrationTable>;

export const kyselyMigrationName = z.string();

export const kyselyMigration = z.object({
  Name: kyselyMigrationName,
  Timestamp: z.string(),
});

export const kyselyMigrationInitializer = z.object({
  Name: kyselyMigrationName,
  Timestamp: z.string(),
});

export const kyselyMigrationMutator = z.object({
  Name: kyselyMigrationName.optional(),
  Timestamp: z.string().optional(),
});
