// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';
import { z } from 'zod';

/** Identifier type for public.kysely_migration_lock */
export type KyselyMigrationLockId = string & { __brand: 'KyselyMigrationLockId' };

/** Represents the table public.kysely_migration_lock */
export default interface KyselyMigrationLockTable {
  /** Database type: pg_catalog.varchar */
  id: ColumnType<KyselyMigrationLockId, KyselyMigrationLockId, KyselyMigrationLockId>;

  /** Database type: pg_catalog.int4 */
  isLocked: ColumnType<number, number | undefined, number>;
}

export type KyselyMigrationLock = Selectable<KyselyMigrationLockTable>;

export type NewKyselyMigrationLock = Insertable<KyselyMigrationLockTable>;

export type KyselyMigrationLockUpdate = Updateable<KyselyMigrationLockTable>;

export const kyselyMigrationLockId = z.string();

export const kyselyMigrationLock = z.object({
  id: kyselyMigrationLockId,
  isLocked: z.number(),
});

export const kyselyMigrationLockInitializer = z.object({
  id: kyselyMigrationLockId,
  isLocked: z.number().optional(),
});

export const kyselyMigrationLockMutator = z.object({
  id: kyselyMigrationLockId.optional(),
  isLocked: z.number().optional(),
});
