// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';
import { z } from 'zod';

/** Identifier type for public.kysely_migration_lock */
export type KyselyMigrationLockId = string & { __brand: 'KyselyMigrationLockId' };

/** Represents the table public.kysely_migration_lock */
export default interface KyselyMigrationLockTable {
  /** Database type: pg_catalog.varchar */
  Id: ColumnType<KyselyMigrationLockId, KyselyMigrationLockId, KyselyMigrationLockId>;

  /** Database type: pg_catalog.int4 */
  IsLocked: ColumnType<number, number | undefined, number>;
}

export type KyselyMigrationLock = Selectable<KyselyMigrationLockTable>;

export type NewKyselyMigrationLock = Insertable<KyselyMigrationLockTable>;

export type KyselyMigrationLockUpdate = Updateable<KyselyMigrationLockTable>;

export const kyselyMigrationLockId = z.string();

export const kyselyMigrationLock = z.object({
  Id: kyselyMigrationLockId,
  IsLocked: z.number(),
});

export const kyselyMigrationLockInitializer = z.object({
  Id: kyselyMigrationLockId,
  IsLocked: z.number().optional(),
});

export const kyselyMigrationLockMutator = z.object({
  Id: kyselyMigrationLockId.optional(),
  IsLocked: z.number().optional(),
});
