// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Represents the enum public.measurement_type */
type MeasurementType = 
  | 'boolean'
  | 'dataframe';

export default MeasurementType;

/** Zod schema for measurement_type */
export const measurementType = z.enum([
  'boolean',
  'dataframe',
]);;
