// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { workspaceId, type WorkspaceId } from './Workspace';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';
import { z } from 'zod';

/** Identifier type for public.model */
export type ModelId = string & { __brand: 'ModelId' };

/** Represents the table public.model */
export default interface ModelTable {
  /** Database type: pg_catalog.text */
  Id: ColumnType<ModelId, ModelId, ModelId>;

  /** Database type: pg_catalog.text */
  Name: ColumnType<string, string, string>;

  /** Database type: pg_catalog.text */
  WorkspaceId: ColumnType<WorkspaceId, WorkspaceId, WorkspaceId>;

  /** Database type: pg_catalog.timestamptz */
  CreatedAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Model = Selectable<ModelTable>;

export type NewModel = Insertable<ModelTable>;

export type ModelUpdate = Updateable<ModelTable>;

export const modelId = z.string();

export const model = z.object({
  Id: modelId,
  Name: z.string(),
  WorkspaceId: workspaceId,
  CreatedAt: z.date(),
});

export const modelInitializer = z.object({
  Id: modelId,
  Name: z.string(),
  WorkspaceId: workspaceId,
  CreatedAt: z.date().optional(),
});

export const modelMutator = z.object({
  Id: modelId.optional(),
  Name: z.string().optional(),
  WorkspaceId: workspaceId.optional(),
  CreatedAt: z.date().optional(),
});
