// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { modelId, type ModelId } from './Model';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';
import { z } from 'zod';

/** Represents the table public.model_relation */
export default interface ModelRelationTable {
  /** Database type: pg_catalog.text */
  parentModelId: ColumnType<ModelId, ModelId, ModelId>;

  /** Database type: pg_catalog.text */
  childModelId: ColumnType<ModelId, ModelId, ModelId>;

  /** Database type: pg_catalog.int8 */
  count: ColumnType<string, string, string>;
}

export type ModelRelation = Selectable<ModelRelationTable>;

export type NewModelRelation = Insertable<ModelRelationTable>;

export type ModelRelationUpdate = Updateable<ModelRelationTable>;

export const modelRelation = z.object({
  parentModelId: modelId,
  childModelId: modelId,
  count: z.string(),
});

export const modelRelationInitializer = z.object({
  parentModelId: modelId,
  childModelId: modelId,
  count: z.string(),
});

export const modelRelationMutator = z.object({
  parentModelId: modelId.optional(),
  childModelId: modelId.optional(),
  count: z.string().optional(),
});
