// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { modelId, type ModelId } from './Model';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';
import { z } from 'zod';

/** Represents the table public.model_relation */
export default interface ModelRelationTable {
  parent_model_id: ColumnType<ModelId, ModelId, ModelId>;

  child_model_id: ColumnType<ModelId, ModelId, ModelId>;
}

export type ModelRelation = Selectable<ModelRelationTable>;

export type NewModelRelation = Insertable<ModelRelationTable>;

export type ModelRelationUpdate = Updateable<ModelRelationTable>;

export const modelRelation = z.object({
  parent_model_id: modelId,
  child_model_id: modelId,
});

export const modelRelationInitializer = z.object({
  parent_model_id: modelId,
  child_model_id: modelId,
});

export const modelRelationMutator = z.object({
  parent_model_id: modelId.optional(),
  child_model_id: modelId.optional(),
});
