// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { userId, type UserId } from './User';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';
import { z } from 'zod';

/** Identifier type for public.oauth_account */
export type OauthAccountProviderId = string & { __brand: 'OauthAccountProviderId' };

/** Identifier type for public.oauth_account */
export type OauthAccountProviderUserId = string & { __brand: 'OauthAccountProviderUserId' };

/** Represents the table public.oauth_account */
export default interface OauthAccountTable {
  /** Database type: pg_catalog.text */
  ProviderId: ColumnType<OauthAccountProviderId, OauthAccountProviderId, OauthAccountProviderId>;

  /** Database type: pg_catalog.text */
  ProviderUserId: ColumnType<OauthAccountProviderUserId, OauthAccountProviderUserId, OauthAccountProviderUserId>;

  /** Database type: pg_catalog.text */
  UserId: ColumnType<UserId, UserId, UserId>;
}

export type OauthAccount = Selectable<OauthAccountTable>;

export type NewOauthAccount = Insertable<OauthAccountTable>;

export type OauthAccountUpdate = Updateable<OauthAccountTable>;

export const oauthAccountProviderId = z.string();

export const oauthAccountProviderUserId = z.string();

export const oauthAccount = z.object({
  ProviderId: oauthAccountProviderId,
  ProviderUserId: oauthAccountProviderUserId,
  UserId: userId,
});

export const oauthAccountInitializer = z.object({
  ProviderId: oauthAccountProviderId,
  ProviderUserId: oauthAccountProviderUserId,
  UserId: userId,
});

export const oauthAccountMutator = z.object({
  ProviderId: oauthAccountProviderId.optional(),
  ProviderUserId: oauthAccountProviderUserId.optional(),
  UserId: userId.optional(),
});
