// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { userId, type UserId } from './User';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';
import { z } from 'zod';

/** Identifier type for public.password_reset_token */
export type PasswordResetTokenId = string & { __brand: 'PasswordResetTokenId' };

/** Represents the table public.password_reset_token */
export default interface PasswordResetTokenTable {
  /** Database type: pg_catalog.text */
  Id: ColumnType<PasswordResetTokenId, PasswordResetTokenId, PasswordResetTokenId>;

  /** Database type: pg_catalog.text */
  UserId: ColumnType<UserId, UserId, UserId>;

  /** Database type: pg_catalog.text */
  Token: ColumnType<string, string, string>;

  /** Database type: pg_catalog.timestamptz */
  ExpiresAt: ColumnType<Date, Date | string, Date | string>;
}

export type PasswordResetToken = Selectable<PasswordResetTokenTable>;

export type NewPasswordResetToken = Insertable<PasswordResetTokenTable>;

export type PasswordResetTokenUpdate = Updateable<PasswordResetTokenTable>;

export const passwordResetTokenId = z.string();

export const passwordResetToken = z.object({
  Id: passwordResetTokenId,
  UserId: userId,
  Token: z.string(),
  ExpiresAt: z.date(),
});

export const passwordResetTokenInitializer = z.object({
  Id: passwordResetTokenId,
  UserId: userId,
  Token: z.string(),
  ExpiresAt: z.date(),
});

export const passwordResetTokenMutator = z.object({
  Id: passwordResetTokenId.optional(),
  UserId: userId.optional(),
  Token: z.string().optional(),
  ExpiresAt: z.date().optional(),
});
