// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { projectId, type ProjectId } from './Project';
import { hardwareId, type HardwareId } from './Hardware';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';
import { z } from 'zod';

/** Represents the table public.project_hardware */
export default interface ProjectHardwareTable {
  /** Database type: pg_catalog.text */
  projectId: ColumnType<ProjectId, ProjectId, ProjectId>;

  /** Database type: pg_catalog.text */
  hardwareId: ColumnType<HardwareId, HardwareId, HardwareId>;
}

export type ProjectHardware = Selectable<ProjectHardwareTable>;

export type NewProjectHardware = Insertable<ProjectHardwareTable>;

export type ProjectHardwareUpdate = Updateable<ProjectHardwareTable>;

export const projectHardware = z.object({
  projectId: projectId,
  hardwareId: hardwareId,
});

export const projectHardwareInitializer = z.object({
  projectId: projectId,
  hardwareId: hardwareId,
});

export const projectHardwareMutator = z.object({
  projectId: projectId.optional(),
  hardwareId: hardwareId.optional(),
});
