// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { userId, type UserId } from './User';
import { workspaceId, type WorkspaceId } from './Workspace';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';
import { z } from 'zod';

/** Represents the table public.secret */
export default interface SecretTable {
  id: ColumnType<string, string, string>;

  user_id: ColumnType<UserId, UserId, UserId>;

  value: ColumnType<string, string, string>;

  workspace_id: ColumnType<WorkspaceId, WorkspaceId, WorkspaceId>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  last_used_at: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type Secret = Selectable<SecretTable>;

export type NewSecret = Insertable<SecretTable>;

export type SecretUpdate = Updateable<SecretTable>;

export const secret = z.object({
  id: z.string(),
  user_id: userId,
  value: z.string(),
  workspace_id: workspaceId,
  created_at: z.date(),
  last_used_at: z.date().nullable(),
});

export const secretInitializer = z.object({
  id: z.string(),
  user_id: userId,
  value: z.string(),
  workspace_id: workspaceId,
  created_at: z.date().optional(),
  last_used_at: z.date().optional().nullable(),
});

export const secretMutator = z.object({
  id: z.string().optional(),
  user_id: userId.optional(),
  value: z.string().optional(),
  workspace_id: workspaceId.optional(),
  created_at: z.date().optional(),
  last_used_at: z.date().optional().nullable(),
});
