// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { measurementId, type MeasurementId } from './Measurement';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';
import { z } from 'zod';

/** Identifier type for public.tag */
export type TagId = string & { __brand: 'TagId' };

/** Represents the table public.tag */
export default interface TagTable {
  /** Database type: pg_catalog.text */
  Id: ColumnType<TagId, TagId, TagId>;

  /** Database type: pg_catalog.text */
  Name: ColumnType<string, string, string>;

  /** Database type: pg_catalog.text */
  MeasurementId: ColumnType<MeasurementId, MeasurementId, MeasurementId>;

  /** Database type: pg_catalog.timestamptz */
  CreatedAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Tag = Selectable<TagTable>;

export type NewTag = Insertable<TagTable>;

export type TagUpdate = Updateable<TagTable>;

export const tagId = z.string();

export const tag = z.object({
  Id: tagId,
  Name: z.string(),
  MeasurementId: measurementId,
  CreatedAt: z.date(),
});

export const tagInitializer = z.object({
  Id: tagId,
  Name: z.string(),
  MeasurementId: measurementId,
  CreatedAt: z.date().optional(),
});

export const tagMutator = z.object({
  Id: tagId.optional(),
  Name: z.string().optional(),
  MeasurementId: measurementId.optional(),
  CreatedAt: z.date().optional(),
});
