// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { measurementId, type MeasurementId } from './Measurement';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';
import { z } from 'zod';

/** Identifier type for public.tag */
export type TagId = string & { __brand: 'TagId' };

/** Represents the table public.tag */
export default interface TagTable {
  id: ColumnType<TagId, TagId, TagId>;

  name: ColumnType<string, string, string>;

  measurement_id: ColumnType<MeasurementId, MeasurementId, MeasurementId>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Tag = Selectable<TagTable>;

export type NewTag = Insertable<TagTable>;

export type TagUpdate = Updateable<TagTable>;

export const tagId = z.string();

export const tag = z.object({
  id: tagId,
  name: z.string(),
  measurement_id: measurementId,
  created_at: z.date(),
});

export const tagInitializer = z.object({
  id: tagId,
  name: z.string(),
  measurement_id: measurementId,
  created_at: z.date().optional(),
});

export const tagMutator = z.object({
  id: tagId.optional(),
  name: z.string().optional(),
  measurement_id: measurementId.optional(),
  created_at: z.date().optional(),
});
