// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { measurementType, type default as MeasurementType } from './MeasurementType';
import { projectId, type ProjectId } from './Project';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';
import { z } from 'zod';

/** Identifier type for public.test */
export type TestId = string & { __brand: 'TestId' };

/** Represents the table public.test */
export default interface TestTable {
  /** Database type: pg_catalog.text */
  Id: ColumnType<TestId, TestId, TestId>;

  /** Database type: public.measurement_type */
  MeasurementType: ColumnType<MeasurementType, MeasurementType, MeasurementType>;

  /** Database type: pg_catalog.text */
  Name: ColumnType<string, string, string>;

  /** Database type: pg_catalog.text */
  ProjectId: ColumnType<ProjectId, ProjectId, ProjectId>;

  /** Database type: pg_catalog.timestamptz */
  CreatedAt: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.timestamptz */
  UpdatedAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Test = Selectable<TestTable>;

export type NewTest = Insertable<TestTable>;

export type TestUpdate = Updateable<TestTable>;

export const testId = z.string();

export const test = z.object({
  Id: testId,
  MeasurementType: measurementType,
  Name: z.string(),
  ProjectId: projectId,
  CreatedAt: z.date(),
  UpdatedAt: z.date(),
});

export const testInitializer = z.object({
  Id: testId,
  MeasurementType: measurementType,
  Name: z.string(),
  ProjectId: projectId,
  CreatedAt: z.date().optional(),
  UpdatedAt: z.date().optional(),
});

export const testMutator = z.object({
  Id: testId.optional(),
  MeasurementType: measurementType.optional(),
  Name: z.string().optional(),
  ProjectId: projectId.optional(),
  CreatedAt: z.date().optional(),
  UpdatedAt: z.date().optional(),
});
