// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { userId, type UserId } from './User';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';
import { z } from 'zod';

/** Identifier type for public.user_session */
export type UserSessionId = string & { __brand: 'UserSessionId' };

/** Represents the table public.user_session */
export default interface UserSessionTable {
  /** Database type: pg_catalog.text */
  Id: ColumnType<UserSessionId, UserSessionId, UserSessionId>;

  /** Database type: pg_catalog.text */
  UserId: ColumnType<UserId, UserId, UserId>;

  /** Database type: pg_catalog.timestamptz */
  ExpiresAt: ColumnType<Date, Date | string, Date | string>;
}

export type UserSession = Selectable<UserSessionTable>;

export type NewUserSession = Insertable<UserSessionTable>;

export type UserSessionUpdate = Updateable<UserSessionTable>;

export const userSessionId = z.string();

export const userSession = z.object({
  Id: userSessionId,
  UserId: userId,
  ExpiresAt: z.date(),
});

export const userSessionInitializer = z.object({
  Id: userSessionId,
  UserId: userId,
  ExpiresAt: z.date(),
});

export const userSessionMutator = z.object({
  Id: userSessionId.optional(),
  UserId: userId.optional(),
  ExpiresAt: z.date().optional(),
});
