// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';
import { z } from 'zod';

/** Identifier type for public.user */
export type UserId = string & { __brand: 'UserId' };

/** Represents the table public.user */
export default interface UserTable {
  /** Database type: pg_catalog.text */
  Id: ColumnType<UserId, UserId, UserId>;

  /** Database type: pg_catalog.bool */
  EmailVerified: ColumnType<boolean | null, boolean | null, boolean | null>;

  /** Database type: pg_catalog.text */
  Email: ColumnType<string, string, string>;

  /** Database type: pg_catalog.text */
  HashedPassword: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.timestamptz */
  CreatedAt: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.timestamptz */
  UpdatedAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type User = Selectable<UserTable>;

export type NewUser = Insertable<UserTable>;

export type UserUpdate = Updateable<UserTable>;

export const userId = z.string();

export const user = z.object({
  Id: userId,
  EmailVerified: z.boolean().nullable(),
  Email: z.string(),
  HashedPassword: z.string().nullable(),
  CreatedAt: z.date(),
  UpdatedAt: z.date(),
});

export const userInitializer = z.object({
  Id: userId,
  EmailVerified: z.boolean().optional().nullable(),
  Email: z.string(),
  HashedPassword: z.string().optional().nullable(),
  CreatedAt: z.date().optional(),
  UpdatedAt: z.date().optional(),
});

export const userMutator = z.object({
  Id: userId.optional(),
  EmailVerified: z.boolean().optional().nullable(),
  Email: z.string().optional(),
  HashedPassword: z.string().optional().nullable(),
  CreatedAt: z.date().optional(),
  UpdatedAt: z.date().optional(),
});
