// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';
import { z } from 'zod';

/** Identifier type for public.user */
export type UserId = string & { __brand: 'UserId' };

/** Represents the table public.user */
export default interface UserTable {
  /** Database type: pg_catalog.text */
  id: ColumnType<UserId, UserId, UserId>;

  /** Database type: pg_catalog.bool */
  emailVerified: ColumnType<boolean | null, boolean | null, boolean | null>;

  /** Database type: pg_catalog.text */
  email: ColumnType<string, string, string>;

  /** Database type: pg_catalog.text */
  hashedPassword: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.timestamptz */
  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.timestamptz */
  updatedAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type User = Selectable<UserTable>;

export type NewUser = Insertable<UserTable>;

export type UserUpdate = Updateable<UserTable>;

export const userId = z.string();

export const user = z.object({
  id: userId,
  emailVerified: z.boolean().nullable(),
  email: z.string(),
  hashedPassword: z.string().nullable(),
  createdAt: z.date(),
  updatedAt: z.date(),
});

export const userInitializer = z.object({
  id: userId,
  emailVerified: z.boolean().optional().nullable(),
  email: z.string(),
  hashedPassword: z.string().optional().nullable(),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
});

export const userMutator = z.object({
  id: userId.optional(),
  emailVerified: z.boolean().optional().nullable(),
  email: z.string().optional(),
  hashedPassword: z.string().optional().nullable(),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
});
