// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { userId, type UserId } from './User';
import { workspaceId, type WorkspaceId } from './Workspace';
import { workspaceRole, type default as WorkspaceRole } from './WorkspaceRole';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';
import { z } from 'zod';

/** Represents the table public.workspace_user */
export default interface WorkspaceUserTable {
  user_id: ColumnType<UserId, UserId, UserId>;

  workspace_id: ColumnType<WorkspaceId, WorkspaceId, WorkspaceId>;

  role: ColumnType<WorkspaceRole, WorkspaceRole, WorkspaceRole>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type WorkspaceUser = Selectable<WorkspaceUserTable>;

export type NewWorkspaceUser = Insertable<WorkspaceUserTable>;

export type WorkspaceUserUpdate = Updateable<WorkspaceUserTable>;

export const workspaceUser = z.object({
  user_id: userId,
  workspace_id: workspaceId,
  role: workspaceRole,
  created_at: z.date(),
});

export const workspaceUserInitializer = z.object({
  user_id: userId,
  workspace_id: workspaceId,
  role: workspaceRole,
  created_at: z.date().optional(),
});

export const workspaceUserMutator = z.object({
  user_id: userId.optional(),
  workspace_id: workspaceId.optional(),
  role: workspaceRole.optional(),
  created_at: z.date().optional(),
});
