// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type HardwareId } from './Hardware';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Represents the table public.hardware_relation */
export default interface HardwareRelationTable {
  /** Database type: pg_catalog.text */
  parentHardwareId: ColumnType<HardwareId, HardwareId, HardwareId>;

  /** Database type: pg_catalog.text */
  childHardwareId: ColumnType<HardwareId, HardwareId, HardwareId>;
}

export type HardwareRelation = Selectable<HardwareRelationTable>;

export type NewHardwareRelation = Insertable<HardwareRelationTable>;

export type HardwareRelationUpdate = Updateable<HardwareRelationTable>;
