// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

export type KyselyMigrationLockId = string;

/** Represents the table public.kysely_migration_lock */
export default interface KyselyMigrationLockTable {
  /** Database type: pg_catalog.varchar */
  id: ColumnType<KyselyMigrationLockId, KyselyMigrationLockId, KyselyMigrationLockId>;

  /** Database type: pg_catalog.int4 */
  isLocked: ColumnType<number, number | undefined, number>;
}

export type KyselyMigrationLock = Selectable<KyselyMigrationLockTable>;

export type NewKyselyMigrationLock = Insertable<KyselyMigrationLockTable>;

export type KyselyMigrationLockUpdate = Updateable<KyselyMigrationLockTable>;
