// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.measurement_type */
type MeasurementType = 
  | 'boolean'
  | 'dataframe'
  | 'scalar';

export default MeasurementType;
