// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ModelId } from './Model';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Represents the table public.model_relation */
export default interface ModelRelationTable {
  /** Database type: pg_catalog.text */
  parentModelId: ColumnType<ModelId, ModelId, ModelId>;

  /** Database type: pg_catalog.text */
  childModelId: ColumnType<ModelId, ModelId, ModelId>;

  /** Database type: pg_catalog.int4 */
  count: ColumnType<number, number, number>;
}

export type ModelRelation = Selectable<ModelRelationTable>;

export type NewModelRelation = Insertable<ModelRelationTable>;

export type ModelRelationUpdate = Updateable<ModelRelationTable>;
