// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type UserId } from './User';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

export type OauthAccountProviderId = string;

export type OauthAccountProviderUserId = string;

/** Represents the table public.oauth_account */
export default interface OauthAccountTable {
  /** Database type: pg_catalog.text */
  providerId: ColumnType<OauthAccountProviderId, OauthAccountProviderId, OauthAccountProviderId>;

  /** Database type: pg_catalog.text */
  providerUserId: ColumnType<OauthAccountProviderUserId, OauthAccountProviderUserId, OauthAccountProviderUserId>;

  /** Database type: pg_catalog.text */
  userId: ColumnType<UserId, UserId, UserId>;
}

export type OauthAccount = Selectable<OauthAccountTable>;

export type NewOauthAccount = Insertable<OauthAccountTable>;

export type OauthAccountUpdate = Updateable<OauthAccountTable>;
