// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type PartVariationId } from './PartVariation';
import { type WorkspaceId } from './Workspace';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Represents the table public.part_variation_relation */
export default interface PartVariationRelationTable {
  /** Database type: pg_catalog.text */
  parentPartVariationId: ColumnType<PartVariationId, PartVariationId, PartVariationId>;

  /** Database type: pg_catalog.text */
  childPartVariationId: ColumnType<PartVariationId, PartVariationId, PartVariationId>;

  /** Database type: pg_catalog.text */
  workspaceId: ColumnType<WorkspaceId, WorkspaceId, WorkspaceId>;

  /** Database type: pg_catalog.int4 */
  count: ColumnType<number, number, number>;
}

export type PartVariationRelation = Selectable<PartVariationRelationTable>;

export type NewPartVariationRelation = Insertable<PartVariationRelationTable>;

export type PartVariationRelationUpdate = Updateable<PartVariationRelationTable>;
