// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type WorkspaceId } from './Workspace';
import { type PartId } from './Part';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

export type PartVariationId = string;

/** Represents the table public.part_variation */
export default interface PartVariationTable {
  /** Database type: pg_catalog.text */
  id: ColumnType<PartVariationId, PartVariationId, PartVariationId>;

  /** Database type: pg_catalog.text */
  workspaceId: ColumnType<WorkspaceId, WorkspaceId, WorkspaceId>;

  /** Database type: pg_catalog.text */
  partId: ColumnType<PartId, PartId, PartId>;

  /** Database type: pg_catalog.text */
  partNumber: ColumnType<string, string, string>;

  /** Database type: pg_catalog.text */
  description: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.timestamptz */
  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type PartVariation = Selectable<PartVariationTable>;

export type NewPartVariation = Insertable<PartVariationTable>;

export type PartVariationUpdate = Updateable<PartVariationTable>;
