// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type WorkspaceId } from './Workspace';
import { type ProductId } from './Product';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

export type PartId = string;

/** Represents the table public.part */
export default interface PartTable {
  /** Database type: pg_catalog.text */
  id: ColumnType<PartId, PartId, PartId>;

  /** Database type: pg_catalog.text */
  workspaceId: ColumnType<WorkspaceId, WorkspaceId, WorkspaceId>;

  /** Database type: pg_catalog.text */
  productId: ColumnType<ProductId, ProductId, ProductId>;

  /** Database type: pg_catalog.text */
  name: ColumnType<string, string, string>;

  /** Database type: pg_catalog.text */
  description: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.timestamptz */
  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Part = Selectable<PartTable>;

export type NewPart = Insertable<PartTable>;

export type PartUpdate = Updateable<PartTable>;
