// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.plan_type */
type PlanType = 
  | 'hobby'
  | 'pro'
  | 'enterprise';

export default PlanType;
