// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type WorkspaceId } from './Workspace';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

export type ProductId = string;

/** Represents the table public.product */
export default interface ProductTable {
  /** Database type: pg_catalog.text */
  id: ColumnType<ProductId, ProductId, ProductId>;

  /** Database type: pg_catalog.text */
  workspaceId: ColumnType<WorkspaceId, WorkspaceId, WorkspaceId>;

  /** Database type: pg_catalog.text */
  name: ColumnType<string, string, string>;

  /** Database type: pg_catalog.text */
  description: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.timestamptz */
  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Product = Selectable<ProductTable>;

export type NewProduct = Insertable<ProductTable>;

export type ProductUpdate = Updateable<ProductTable>;
