// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.project_role */
type ProjectRole = 
  | 'operator'
  | 'developer';

export default ProjectRole;
