// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.project_role */
type ProjectRole = 
  | 'test'
  | 'dev'
  | 'pending';

export default ProjectRole;
