// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ProjectId } from './Project';
import { type UnitId } from './Unit';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Represents the table public.project_unit */
export default interface ProjectUnitTable {
  /** Database type: pg_catalog.text */
  projectId: ColumnType<ProjectId, ProjectId, ProjectId>;

  /** Database type: pg_catalog.text */
  unitId: ColumnType<UnitId, UnitId, UnitId>;
}

export type ProjectUnit = Selectable<ProjectUnitTable>;

export type NewProjectUnit = Insertable<ProjectUnitTable>;

export type ProjectUnitUpdate = Updateable<ProjectUnitTable>;
