// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ProjectId } from './Project';
import { type HardwareId } from './Hardware';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Represents the table public.project_hardware */
export default interface ProjectHardwareTable {
  /** Database type: pg_catalog.text */
  projectId: ColumnType<ProjectId, ProjectId, ProjectId>;

  /** Database type: pg_catalog.text */
  hardwareId: ColumnType<HardwareId, HardwareId, HardwareId>;
}

export type ProjectHardware = Selectable<ProjectHardwareTable>;

export type NewProjectHardware = Insertable<ProjectHardwareTable>;

export type ProjectHardwareUpdate = Updateable<ProjectHardwareTable>;
