// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type WorkspaceId } from './Workspace';
import { type PartVariationId } from './PartVariation';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

export type ProjectId = string;

/** Represents the table public.project */
export default interface ProjectTable {
  /** Database type: pg_catalog.text */
  id: ColumnType<ProjectId, ProjectId, ProjectId>;

  /** Database type: pg_catalog.text */
  name: ColumnType<string, string, string>;

  /** Database type: pg_catalog.text */
  workspaceId: ColumnType<WorkspaceId, WorkspaceId, WorkspaceId>;

  /** Database type: pg_catalog.text */
  partVariationId: ColumnType<PartVariationId, PartVariationId, PartVariationId>;

  /** Database type: pg_catalog.timestamptz */
  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.timestamptz */
  updatedAt: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.text */
  repoUrl: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.int4 */
  numCycles: ColumnType<number, number | undefined, number>;
}

export type Project = Selectable<ProjectTable>;

export type NewProject = Insertable<ProjectTable>;

export type ProjectUpdate = Updateable<ProjectTable>;
