// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type UserId } from './User';
import { type ProjectId } from './Project';
import { type WorkspaceId } from './Workspace';
import { type default as ProjectRole } from './ProjectRole';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Represents the table public.project_user */
export default interface ProjectUserTable {
  /** Database type: pg_catalog.text */
  userId: ColumnType<UserId, UserId, UserId>;

  /** Database type: pg_catalog.text */
  projectId: ColumnType<ProjectId, ProjectId, ProjectId>;

  /** Database type: pg_catalog.text */
  workspaceId: ColumnType<WorkspaceId, WorkspaceId, WorkspaceId>;

  /** Database type: public.project_role */
  role: ColumnType<ProjectRole, ProjectRole, ProjectRole>;

  /** Database type: pg_catalog.timestamptz */
  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type ProjectUser = Selectable<ProjectUserTable>;

export type NewProjectUser = Insertable<ProjectUserTable>;

export type ProjectUserUpdate = Updateable<ProjectUserTable>;
