// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.revision_type */
type RevisionType = 
  | 'init'
  | 'remove'
  | 'add';

export default RevisionType;
