// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type HardwareId } from './Hardware';
import { type UserId } from './User';
import { type ProjectId } from './Project';
import { type StationId } from './Station';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

export type SessionId = string;

/** Represents the table public.session */
export default interface SessionTable {
  /** Database type: pg_catalog.text */
  id: ColumnType<SessionId, SessionId, SessionId>;

  /** Database type: pg_catalog.text */
  hardwareId: ColumnType<HardwareId, HardwareId, HardwareId>;

  /** Database type: pg_catalog.text */
  userId: ColumnType<UserId | null, UserId | null, UserId | null>;

  /** Database type: pg_catalog.text */
  projectId: ColumnType<ProjectId, ProjectId, ProjectId>;

  /** Database type: pg_catalog.text */
  stationId: ColumnType<StationId, StationId, StationId>;

  /** Database type: pg_catalog.text */
  commitHash: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.bool */
  integrity: ColumnType<boolean, boolean, boolean>;

  /** Database type: pg_catalog.bool */
  aborted: ColumnType<boolean, boolean, boolean>;

  /** Database type: pg_catalog.text */
  notes: ColumnType<string | null, string | null, string | null>;

  /** Database type: pg_catalog.timestamptz */
  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Session = Selectable<SessionTable>;

export type NewSession = Insertable<SessionTable>;

export type SessionUpdate = Updateable<SessionTable>;
