// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.storage_provider */
type StorageProvider = 
  | 's3'
  | 'postgres';

export default StorageProvider;
