// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type WorkspaceId } from './Workspace';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

export type TagId = string;

/** Represents the table public.tag */
export default interface TagTable {
  /** Database type: pg_catalog.text */
  id: ColumnType<TagId, TagId, TagId>;

  /** Database type: pg_catalog.text */
  name: ColumnType<string, string, string>;

  /** Database type: pg_catalog.text */
  workspaceId: ColumnType<WorkspaceId, WorkspaceId, WorkspaceId>;

  /** Database type: pg_catalog.timestamptz */
  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Tag = Selectable<TagTable>;

export type NewTag = Insertable<TagTable>;

export type TagUpdate = Updateable<TagTable>;
