// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type default as MeasurementType } from './MeasurementType';
import { type ProjectId } from './Project';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

export type TestId = string;

/** Represents the table public.test */
export default interface TestTable {
  /** Database type: pg_catalog.text */
  id: ColumnType<TestId, TestId, TestId>;

  /** Database type: public.measurement_type */
  measurementType: ColumnType<MeasurementType, MeasurementType, MeasurementType>;

  /** Database type: pg_catalog.text */
  name: ColumnType<string, string, string>;

  /** Database type: pg_catalog.text */
  projectId: ColumnType<ProjectId, ProjectId, ProjectId>;

  /** Database type: pg_catalog.timestamptz */
  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.timestamptz */
  updatedAt: ColumnType<Date, Date | string | undefined, Date | string>;

  /** Database type: pg_catalog.text */
  unit: ColumnType<string | null, string | null, string | null>;
}

export type Test = Selectable<TestTable>;

export type NewTest = Insertable<TestTable>;

export type TestUpdate = Updateable<TestTable>;
