// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type UnitId } from './Unit';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Represents the table public.unit_relation */
export default interface UnitRelationTable {
  /** Database type: pg_catalog.text */
  parentUnitId: ColumnType<UnitId, UnitId, UnitId>;

  /** Database type: pg_catalog.text */
  childUnitId: ColumnType<UnitId, UnitId, UnitId>;
}

export type UnitRelation = Selectable<UnitRelationTable>;

export type NewUnitRelation = Insertable<UnitRelationTable>;

export type UnitRelationUpdate = Updateable<UnitRelationTable>;
