// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.workspace_role */
type WorkspaceRole = 
  | 'owner'
  | 'admin'
  | 'member'
  | 'pending';

export default WorkspaceRole;
