// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type UserId } from './User';
import { type WorkspaceId } from './Workspace';
import { type default as WorkspaceRole } from './WorkspaceRole';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Represents the table public.workspace_user */
export default interface WorkspaceUserTable {
  /** Database type: pg_catalog.text */
  userId: ColumnType<UserId, UserId, UserId>;

  /** Database type: pg_catalog.text */
  workspaceId: ColumnType<WorkspaceId, WorkspaceId, WorkspaceId>;

  /** Database type: public.workspace_role */
  role: ColumnType<WorkspaceRole, WorkspaceRole, WorkspaceRole>;

  /** Database type: pg_catalog.timestamptz */
  createdAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type WorkspaceUser = Selectable<WorkspaceUserTable>;

export type NewWorkspaceUser = Insertable<WorkspaceUserTable>;

export type WorkspaceUserUpdate = Updateable<WorkspaceUserTable>;
