name: Build

on:
  push:
    branches:
      - main
      - staging
  pull_request:

jobs:
  cloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: extractions/setup-just@v1

      - name: Install
        run: just install-bun

      - name: Build
        run: just build
