name: Style Check

on:
  - push
  - pull_request

jobs:
  prettier-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - uses: extractions/setup-just@v1

      - name: Install
        run: just install

      - name: Check
        run: just check
