name: Code Style Check

on:
  - push
  - pull_request

jobs:
  prettier-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Prettier Check
        run: bun format:check
