name: Code Style

on:
  - push
  - pull_request

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
      - uses: abatilo/actions-poetry@v2

      - uses: actions/cache@v3
        with:
          path: ./packages/python/.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - uses: extractions/setup-just@v1

      - name: Install
        run: just install-poetry

      - name: Check
        run: just check-ruff

  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - uses: extractions/setup-just@v1

      - name: Install
        run: just install-bun

      - name: Check
        run: just check-prettier
